name: Build Native Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Clean prebuilds
        shell: bash
        run: |
          if [ -d prebuilds ]; then rm -rf prebuilds/*; fi

      - name: Build with prebuildify
        run: npm run prebuild

      - name: Upload prebuilds to artifact
        uses: actions/upload-artifact@v4
        with:
          name: prebuild-${{ runner.os }}
          path: prebuilds/